name: Release
run-name: Release-${{ github.ref_name }}-${{ github.run_number }}

permissions:
  contents: write

concurrency:
  group: branch-${{ github.ref_name }}
  cancel-in-progress: true

on:
  workflow_dispatch:
  push:
    tags:
    - 'v[0-9]+.[0-9]+.[0-9]+*'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v4

      - name: Setup Golang
        uses: actions/setup-go@v5
        with:
          go-version: 1.24.3

      - name: Install dependencies
        run: go mod download -x

      - name: Build
        run: |
          go build -v -o vault-plugin-database-rabbitmq-linux-amd64 \
          -ldflags "-X github.com/zigmund/vault-plugin-database-rabbitmq/plugin.Version=${{ github.ref_name }}" \
          main.go

      - name: generate sha256sums
        run: |
          sha256sum vault-plugin-database-rabbitmq-linux-amd64 > sha256sums

      - id: artifact-upload
        uses: actions/upload-artifact@v4
        with:
          name: binary
          if-no-files-found: error
          compression-level: 0
          overwrite: true
          path: |
            vault-plugin-database-rabbitmq-linux-amd64
            sha256sums

  release:
    name: Release
    runs-on: ubuntu-latest
    needs:
    - build
    steps:
    - uses: actions/download-artifact@v4
      with:
        name: binary

    - uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ github.ref_name }}
        generate_release_notes: true
        make_latest: true
        prerelease: false
        files: |
          vault-plugin-database-rabbitmq-linux-amd64
          sha256sums
